#!/bin/sh

#============================================================================
# chapter-extract
# Kapitel-auszug
# Kapitel aus einer Video- oder Audiodatei extrahieren und als CSV-Datei speichern
#============================================================================

# Abhängigkeiten:
# ffprobe awk

#============================================================================
# Skriptnutzung
#============================================================================

usage () {
# Wenn das Argument an die Funktion übergeben wird, echo es
[ -z "${1}" ] || echo "! ${1}"
# Hilfe anzeigen
echo "\
Extrahieren Sie Kapitel aus einer Video- oder Audiodatei und speichern Sie sie als CSV-Datei
$(basename "$0") -i eingabe -o ausgabe"
exit 2
}


#============================================================================
# Fehlermeldungen
#============================================================================

INVALID_OPT_ERR='Ungültige Option:'
REQ_ARG_ERR='Erfordert ein Argument'
WRONG_ARGS_ERR='Falsche Anzahl an Argumenten an Skript übergeben'


#============================================================================
# Überprüfen Sie die Anzahl der an das Skript übergebenen Argumente
#============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#============================================================================
# getopts überprüft die an das Skript übergebenen Optionen
#============================================================================

while getopts ':i:o:h' opt
do
  case ${opt} in
     i) input="${OPTARG}";;
     h) usage;;
     o) output="${OPTARG}";;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#============================================================================
# Variablen
#============================================================================

# Namen der Eingabedatei abrufen
input_nopath="${input##*/}"
input_name="${input_nopath%.*}"

# Name der Ausgabedatei
output_default="${input_name}-kapitel.txt"

#============================================================================
# Sexagesimalfunktion
#============================================================================

extract () {
ffprobe -v panic -hide_banner \
-show_chapters -sexagesimal -of csv \
-i "${input}" \
| awk -F "," '{
          time = $5
          chapter = $NF
          if (time ~ /:/) {
            split(time, t, ".")
            sexagesimal = t[1]
          }
          printf("%s,%s\n"), sexagesimal, chapter
}' > "${output:=${output_default}}"
}


#============================================================================
# Funktion ausführen
#============================================================================

extract
